name: ci
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: ['24', '25']
        elixir: ['1.13.4', '1.14']
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.elixir}}
          otp-version: ${{matrix.otp}}
          version-type: loose
      - run: mix deps.get
      - run: mix credo
      - run: mix format --check-formatted
      - run: mix test
